name: test-worklow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: List Files in Repo
        run: |
          echo "Repo ${{github.repository}} contains the following files:"
          tree
